package com.dlfc.zfgj.repositories;

import com.dlfc.zfgj.model.User;
import com.dlfc.zfgj.model.UserExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_user
     *
     * @mbg.generated Tue Feb 21 09:31:29 CST 2017
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_user
     *
     * @mbg.generated Tue Feb 21 09:31:29 CST 2017
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_user
     *
     * @mbg.generated Tue Feb 21 09:31:29 CST 2017
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_user
     *
     * @mbg.generated Tue Feb 21 09:31:29 CST 2017
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_user
     *
     * @mbg.generated Tue Feb 21 09:31:29 CST 2017
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_user
     *
     * @mbg.generated Tue Feb 21 09:31:29 CST 2017
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_user
     *
     * @mbg.generated Tue Feb 21 09:31:29 CST 2017
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);
}