package com.dlfc.zfgj.mapper;

import com.dlfc.admin.common.persistence.annotation.MyBatisDao;
import com.dlfc.zfgj.entity.AgtEmpInfo;
import com.dlfc.zfgj.entity.AgtEmpInfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

@MyBatisDao
public interface AgtEmpInfoMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_emp_info
	 * @mbggenerated  Mon Aug 22 15:10:16 CST 2016
	 */
	int countByExample(AgtEmpInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_emp_info
	 * @mbggenerated  Mon Aug 22 15:10:16 CST 2016
	 */
	int deleteByExample(AgtEmpInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_emp_info
	 * @mbggenerated  Mon Aug 22 15:10:16 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_emp_info
	 * @mbggenerated  Mon Aug 22 15:10:16 CST 2016
	 */
	int insert(AgtEmpInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_emp_info
	 * @mbggenerated  Mon Aug 22 15:10:16 CST 2016
	 */
	int insertSelective(AgtEmpInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_emp_info
	 * @mbggenerated  Mon Aug 22 15:10:16 CST 2016
	 */
	List<AgtEmpInfo> selectByExample(AgtEmpInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_emp_info
	 * @mbggenerated  Mon Aug 22 15:10:16 CST 2016
	 */
	AgtEmpInfo selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_emp_info
	 * @mbggenerated  Mon Aug 22 15:10:16 CST 2016
	 */
	int updateByExampleSelective(@Param("record") AgtEmpInfo record, @Param("example") AgtEmpInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_emp_info
	 * @mbggenerated  Mon Aug 22 15:10:16 CST 2016
	 */
	int updateByExample(@Param("record") AgtEmpInfo record, @Param("example") AgtEmpInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_emp_info
	 * @mbggenerated  Mon Aug 22 15:10:16 CST 2016
	 */
	int updateByPrimaryKeySelective(AgtEmpInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agt_emp_info
	 * @mbggenerated  Mon Aug 22 15:10:16 CST 2016
	 */
	int updateByPrimaryKey(AgtEmpInfo record);

	AgtEmpInfo findByEid(String eId);
	
	//通过公司和排序方式查询首页经纪人列表
	AgtEmpInfo getAgent(AgtEmpInfo record);
	
	//条件查询获取经纪人列表
	List<AgtEmpInfo> selectAgentList(AgtEmpInfo record);
	
	/**
	 * 查询全部信息
	 * @param example
	 * @return
	 */
	List<AgtEmpInfo> selectByExampleAll(AgtEmpInfoExample example);
	
	/**
	 * 查询成交历史数
	 * 
	 * @param aei 存放参数实体
	 * @return 成交历史数
	 */
	int getHistoryDeal(Map<String, Object> aei);
}